---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.17.1

executors:
  # This must match .promu.yml.
  golang:
    docker:
    - image: cimg/go:1.24

jobs:
  test:
    executor: golang

    steps:
    - prometheus/setup_environment
    - run: GOHOSTARCH=386 GOARCH=386 make test
    - run: make
    - prometheus/store_artifact:
        file: gaussdb_exporter

  integration:
    docker:
    - image: cimg/go:1.24
    - image: << parameters.gaussdb_image >>
      environment:
        GS_DB: circle_test
        GS_USER: gaussdb
        GS_PASSWORD: Gaussdb@123!

    parameters:
      gaussdb_image:
        type: string

    environment:
      DATA_SOURCE_NAME: 'gaussdb://gaussdb:Gaussdb@123!@localhost:5432/circle_test?sslmode=disable'
      GOOPTS: '-v -tags integration'

    steps:
    - checkout
    - setup_remote_docker
    - run: docker version
    - run: make build
    - run: make test

workflows:
  version: 2
  gaussdb_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - integration:
        matrix:
          parameters:
            gaussdb_image:
            - opengauss/opengauss:7.0.0-RC1.B023
    - prometheus/build:
        name: build
        parallelism: 3
        promu_opts: "-p linux/amd64 -p windows/amd64 -p linux/arm64 -p darwin/amd64 -p darwin/arm64 -p linux/386"
        filters:
          tags:
            ignore: /^v.*/
          branches:
            ignore: /^(main|master|release-.*|.*build-all.*)$/
    - prometheus/build:
        name: build_all
        parallelism: 12
        filters:
          branches:
            only: /^(main|master|release-.*|.*build-all.*)$/
          tags:
            only: /^v.*/
    - prometheus/publish_master:
        context: org-context
        # docker_hub_organization: prometheuscommunity
        docker_hub_organization: moseszane
        quay_io_organization: prometheuscommunity
        requires:
        - test
        - build_all
        filters:
          branches:
            only: master
    - prometheus/publish_release:
        context: org-context
        # docker_hub_organization: prometheuscommunity
        docker_hub_organization: moseszane
        quay_io_organization: prometheuscommunity
        requires:
        - test
        - build_all
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
